In [1]:
import numpy as np

In [2]:
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])

In [3]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [4]:
b

array([0, 1, 2])

In [5]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [6]:
np.empty((4, 3))

array([[0.00000000e+000, 1.00937611e-320, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.69776220e-062],
       [5.27726147e-091, 7.92560434e+165, 3.54772658e-062],
       [2.57279074e+184, 3.99910963e+252, 1.46030983e-319]])

In [7]:
# a.reshape((4, 1))

In [8]:
# np.random.seed(3)

In [9]:
a = np.random.rand(4)

In [10]:
a

array([0.6318656 , 0.25302755, 0.7871324 , 0.01599618])

In [11]:
b = np.random.rand(4)

In [12]:
b

array([0.5740219 , 0.86414323, 0.25785659, 0.73907937])

In [18]:
np.random.random(100)

array([0.89037557, 0.12589641, 0.98836985, 0.54048889, 0.87072584,
       0.89160877, 0.27823625, 0.51033839, 0.84906344, 0.46666386,
       0.459406  , 0.84384707, 0.84099713, 0.44038854, 0.35638323,
       0.61110877, 0.32609712, 0.80139471, 0.9391015 , 0.91459125,
       0.8627966 , 0.83846964, 0.38100515, 0.76186609, 0.89145481,
       0.03925845, 0.06631079, 0.43502088, 0.70169179, 0.35219472,
       0.85383483, 0.37292753, 0.1193675 , 0.35328745, 0.42696387,
       0.074104  , 0.07151108, 0.00302016, 0.31578909, 0.28668744,
       0.62191385, 0.61366368, 0.49496738, 0.04341826, 0.42395587,
       0.20553923, 0.16528768, 0.72908666, 0.97889405, 0.59554334,
       0.86965728, 0.04762149, 0.02968636, 0.94662524, 0.46084129,
       0.83525706, 0.84243536, 0.00296842, 0.07215983, 0.62557897,
       0.18519177, 0.3862728 , 0.49874905, 0.86050086, 0.44263542,
       0.07407483, 0.53044096, 0.25315759, 0.59816604, 0.42530017,
       0.05546251, 0.18999741, 0.07127201, 0.96739133, 0.00513

In [19]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [21]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [22]:
#cons of python list
print('1.) ')

In [25]:
data = np.array([[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]])

In [26]:
data

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [29]:
data[2:5:2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [31]:
data[4:, 4:]

array([[44, 45],
       [54, 55]])

In [34]:
k = data.copy()

In [35]:
k[4:, 4:] = 5

In [36]:
k

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43,  5,  5],
       [50, 51, 52, 53,  5,  5]])

In [37]:
data

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [52]:
# create an array with 1 border  other was 0
data = np.ones((100, 100), dtype=int)
data[1:-1, 1:-1] = 0


In [53]:
data

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [55]:
for x in data:
    print(*x, sep='')

1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [56]:
python

NameError: name 'python' is not defined